import { TQuestion } from "../types/type"

export const carBrands = [
  "Acura",
  "Alfa",
  "Audi",
  "BMW",
  "Bentley",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Fiat",
  "Ford",
  "GMC",
  "Genesis",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Land",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Maserati",
  "Mazda",
  "Mercedes-Benz",
  "Mercury",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Ram",
  "Rivian",
  "Rolls-Royce",
  "Saab",
  "Saturn",
  "Scion",
  "Smart",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
]

export const questionsList: TQuestion[] = [
  {
    number: 1,
    type: "short-answer",
    question: "How old are you?",
  },
  {
    number: 2,
    type: "dropdown",
    question: "What is your gender?",
    options: ["male", "female", "others"],
  },
  {
    number: 3,
    type: "multi-choice",
    question: "Do you own a car driving license?",
    options: ["Yes", "No, I prefer using other transportation means"],
  },
  {
    number: 4,
    type: "multi-choice",
    question: "Is this your first car?",
    options: ["Yes", "No"],
  },
  {
    number: 5,
    type: "multi-choice",
    question: "Which drivetrain do you prefer?",
    options: ["FWD", "RWD", "I don't know"],
  },
  {
    number: 6,
    type: "multi-choice",
    question: "Are you worried about fuel emission?",
    options: ["Yes", "No"],
  },
  {
    number: 7,
    type: "short-answer",
    question: "How many cars dow you have in your family?",
  },
  {
    number: 8,
    type: "dual",
    question: "Which car make and model do you drive?",
    make: carBrands,
  },
]
